/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main.GUI;

import com.mysql.cj.x.protobuf.MysqlxSql;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Tharun
 */
public class RegistrationPage extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Signup
     */
    public RegistrationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        regEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        regUpassword = new javax.swing.JPasswordField();
        btnSignup1 = new javax.swing.JButton();
        btnSignin1 = new javax.swing.JButton();
        regUname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regEmail.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        regEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEmailActionPerformed(evt);
            }
        });
        jPanel2.add(regEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 240, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        regUpassword.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        regUpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regUpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(regUpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 240, 30));

        btnSignup1.setBackground(new java.awt.Color(255, 153, 51));
        btnSignup1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        btnSignup1.setText("SIGN UP");
        btnSignup1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 130, 40));

        btnSignin1.setBackground(new java.awt.Color(255, 153, 51));
        btnSignin1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        btnSignin1.setText("LOGIN");
        btnSignin1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnSignin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 120, 40));

        regUname.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        regUname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUnameActionPerformed(evt);
            }
        });
        jPanel2.add(regUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 240, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel14.setText("USERNAME :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel4.setText("PASSWORD  :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel5.setText("HAVE AN ACCOUNT?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\athar\\Downloads\\smile2.jpg")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 550));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel2.setText("EMAIL : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, 30));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel3.setText("SMILE GAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 280, 70));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel6.setText("REGISTRATION");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmailActionPerformed

    private void regUpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUpasswordActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        // TODO add your handling code here:
        try {
            String query = "INSERT INTO `signin`(`Username`, `Email`, `Password`,`score`) VALUES (?,?,?,0)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_account", "root", "");
            pst = conn.prepareStatement(query);

            pst.setString(1, regUname.getText());
            pst.setString(2, regEmail.getText());
            pst.setString(3, regUpassword.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Register Successfully");

            LoginPage SignIn = new LoginPage();
            SignIn.show();

            dispose();

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_btnSignup1ActionPerformed

    private void btnSignin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignin1ActionPerformed
        // TODO add your handling code here:+
        LoginPage SignIn = new LoginPage();
        SignIn.show();

        dispose();
    }//GEN-LAST:event_btnSignin1ActionPerformed

    private void regUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin1;
    private javax.swing.JButton btnSignup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField regEmail;
    private javax.swing.JTextField regUname;
    private javax.swing.JPasswordField regUpassword;
    // End of variables declaration//GEN-END:variables
}
